config/routes.rb
Rails.application.routes.draw do
  get "/home", to: "pages#home"
  resources :charges
  authenticated :user do
    root to: 'bakeries#index'
  end
  unauthenticated :user do
    devise_scope :user do
      get '/' => 'devise/sessions#new'
    end
  end
  devise_for :users
  resources :bakeries, only: [:index, :show]
  post "/add_to_basket", to: "orders#add_to_basket"
  get "/my_orders", to: "orders#my_orders"
  get '/home', to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/bakery.rb
class Bakery < ApplicationRecord
  has_many :products
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :bakery
  has_many :baskets, dependent: :destroy
  has_many :products, through: :baskets

  enum status: {
    pending: 0,
    closed: 1
  }

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :bakery
  validates :name, :details, :price, presence: true
  has_many :baskets, dependent: :destroy
  # has_many_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders

  def current_order
    orders.pending.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bakeries_controller.rb
class BakeriesController < ApplicationController
  def index
    @bakeries = Bakery.all
    @markers = @bakeries.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
  end

  def show
    @bakeries = Bakery.find(params[:id])
  end

  private

  # def product_params
  #   params.require(:product).permit(:name, :details, :price, :discription, :photo)
  # end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def my_orders
    @products = current_user.current_order.products
    @total_price = @products.sum(&:price)
    # raise
  end

  # def products
  #   @products = Product.all
  # end

  def add_to_basket
    @product = Product.find(params[:product_id])
    @order = Order.find_or_create_by(user: current_user, status: :pending, bakery: @product.bakery)
    @basket = Basket.create(order: @order, product: @product)
      redirect_to my_orders_path
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :product_id, :bakery_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @bakeries = Bakery.all
    @markers = @bakeries.geocoded.map do |bakery|
      {
        lat: bakery.latitude,
        lng: bakery.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bakery: bakery }),
        image_url: helpers.asset_url("map.png")
      }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bakeries/index.html.erb
<%= render 'shared/navbar' %>
<section>
  <div id="map2"></div>

  <div class="cards-bakery">
    <ul>
      <% @bakeries.each do |bakery| %>
        <a href="<%= bakery_path(bakery) %>">

          <div class="card-bakery" style="text-align: center">
            <div class="img-bakery">
              <img src="<%= bakery.street %>" alt="">
            </div>
            <div class="bakery_address">
              <h2 style="align-items:center;"><li><%= bakery.name %></li></h2>
              <p><li><%= bakery.address %></li></p>
            </div>
          </div>
        </a>
      <% end %>
    </ul>
  </div>
</section>

app/views/bakeries/show.html.erb
<img src="<%= @bakeries.street %>" alt="" id="pig">
<%= link_to bakeries_path do %>
  <ion-icon name="ios-arrow-dropleft" class="arrow-back"></ion-icon>
<% end %>
<div class="bakery_card">
  <h1><%= @bakeries.name %></h1>
  <p><%= @bakeries.address %></p>
  <p id="bakery-description"><%= @bakeries.discription%></p>
</div>

<% @bakeries.products.each do |product| %>
  <div class="card-product">
    <div class="img-product">
      <img src="<%= product.img %>" class="pic">
    </div>
    <div class="card-product-infos">
      <div class="add-product">
        <%= link_to '+', add_to_basket_path(product_id: product.id), method: :post %>
      </div>
          <h2><%= product.name %></h2>
          <span class="product-detail">
            <% a = product.details.split(",") %>
            <% a.each do |product| %>
              <p><%= product %></p>
            <% end %>
          </span>
          <p class="product-price"><%= product.price %>0 CHF</p>
    </div>
  </div>
<% end %>

app/views/charges/create.html.erb
<div class="holder">
  <div class="card-stripe">
    <div class="content-stripe">
      <section class="create-check">
        <div class="icon-check">
          <ion-icon name="checkbox-outline"></ion-icon>
        </div>

        <h1>Your payment <span id="number-order">#<%= rand(100 .. 1000) %> </span> is accepted !</h1>

        <div class="qr-code">
          <p>Your QR code</p>
          <img src="http://cdn.onlinewebfonts.com/svg/img_462691.png">
        </div>
        <div class="button-backhome">
          <a href="/bakeries">Continue your shopping</a>
        </div>
      </section>
    </div>
  </div>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Camilo Breakfast Sàrl"
            data-amount="500"
            data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamiloBreakfast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%# Icon - CSS.GG %>
    <link href='https://css.gg/css' rel='stylesheet'>
  </head>

  <body>
    <%# <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>CamiloBreakfast</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
      <%# Icon - CSS.GG %>
      <link href='https://css.gg/css' rel='stylesheet'>
    </head>
    <body>
      <%= yield %>
    <script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
    </body>
  </html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamiloBreakfast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <div class="banner" style="background-image: url(https://images.unsplash.com/photo-1517433367423-c7e5b0f35086?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1001&q=80);">
      <%= image_tag "camilo.png", alt: "blabla" %>
      <div class="devise-wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/orders/my_orders.html.erb
<%= render 'shared/navbar' %>
<div class="nbar"><h1><strong>My Orders</strong></h1></div>

<% @products.each do |product| %>
  <div class="card-product">
    <div class="img-product">
      <img src="<%= product.img %>" class="pic">
    </div>
    <div class="card-product-infos">
      <h2><%= product.name %></h2>
      <span class="product-detail">
        <% a = product.details.split(",") %>
        <% a.each do |product| %>
          <p><%= product %></p>
        <% end %>
      </span>
      <p class="product-price"><%= product.price %>0 CHF</p>
    </div>
  </div>
<% end %>
<%# <div class="order-bottom"> %>
  <div class="total"> <h3><strong>Total : <%=@total_price %>0 CHF</strong></h3></div>
  <span class="disply-button-stripe">
    <div class="button-pay-stripe">
      <%= form_tag charges_path do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Camilo Breakfast"
                  data-amount=""
                  data-locale="auto"></script>
      <% end %>
    </div>
  </span>
<%# </div> %>

app/views/pages/_info_window.html.erb
<div class="popup-mapbox">
  <%= link_to bakery_path(bakery) do%>
    <h2><%= bakery.name %></h2>
    <p><%= bakery.address %></p>
  <% end %>
</div>

app/views/pages/home.html.erb
<section>
  <div id="map">
    <div id="mapi"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="bottom_navbar">
  <ul>
    <li>
      <a href="<%= home_path %>">
        <% if current_page?(home_path)%>
          <ion-icon name="ios-pin" class="button-selec"></ion-icon>
        <% else %>
          <ion-icon name="ios-pin" ></ion-icon>
        <% end %>
      </a>
    </li>
    <li>
      <a href="<%= bakeries_path %>">
        <% if current_page?(bakeries_path)%>
          <ion-icon name="ios-list" class="button-selec"></ion-icon>
        <% else %>
          <ion-icon name="ios-list"></ion-icon>
        <% end %>
      </a>
    </li>
    <li>
      <a href="<%=  my_orders_path %>">
        <% if current_page?(my_orders_path)%>
          <ion-icon name="ios-cart" class="button-selec"></ion-icon>
        <% else %>
          <ion-icon name="ios-cart"></ion-icon>
        <% end %>
      </a>
    </li>
    <li>
      <% if user_signed_in? %>
        <%= link_to '<ion-icon name="ios-log-out"></ion-icon>'.html_safe, destroy_user_session_path, method: :delete %>
      <% else %>
        <a href="<%= user_session_path %>">
          <ion-icon name="ios-person"></ion-icon>
        </a>
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "bakeries_path", class: "logo-camilo" do %>
      <%= image_tag "logo-camilo.svg" %>
    <% end %>
  </div>
</div>